name: Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    # Run at 22:00 every day
    - cron: '0 22 * * *'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # https://github.com/rust-lang/mdBook/releases/tag/v0.4.40
      MDBOOK_VERSION: 0.4.21
      # https://github.com/badboy/mdbook-toc/releases/tag/0.14.2
      MDBOOK_TOC_VERSION: 0.14.2
      # https://github.com/lambdalisue/rs-mdbook-alerts/releases/tag/v0.5.2
      MDBOOK_ALERTS_VERSION: 0.5.2
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Setup mdbook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: ${{ env.MDBOOK_VERSION }}

      - name: Install mdbook plugins
        run: |
          cargo install mdbook-toc --version ${{ env.MDBOOK_TOC_VERSION }}
          cargo install mdbook-alerts --version ${{ env.MDBOOK_ALERTS_VERSION }}

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "dev-guide/gh-actions-cache"
    
      - name: Build dev-guide
        run: |
          mdbook build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
